// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.7.1
// source: datamodel.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActorStatus int32

const (
	ActorStatus_UNKNOWN_ACTOR_STATE ActorStatus = 0
	ActorStatus_PENDING             ActorStatus = 1
	ActorStatus_SUCCESS             ActorStatus = 2
	ActorStatus_CANCELED            ActorStatus = 3
)

// Enum value maps for ActorStatus.
var (
	ActorStatus_name = map[int32]string{
		0: "UNKNOWN_ACTOR_STATE",
		1: "PENDING",
		2: "SUCCESS",
		3: "CANCELED",
	}
	ActorStatus_value = map[string]int32{
		"UNKNOWN_ACTOR_STATE": 0,
		"PENDING":             1,
		"SUCCESS":             2,
		"CANCELED":            3,
	}
)

func (x ActorStatus) Enum() *ActorStatus {
	p := new(ActorStatus)
	*p = x
	return p
}

func (x ActorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_datamodel_proto_enumTypes[0].Descriptor()
}

func (ActorStatus) Type() protoreflect.EnumType {
	return &file_datamodel_proto_enumTypes[0]
}

func (x ActorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorStatus.Descriptor instead.
func (ActorStatus) EnumDescriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{0}
}

type Run_Result int32

const (
	Run_UNKNOWN               Run_Result = 0
	Run_FAILED_PRECONDITION   Run_Result = 1
	Run_FAILED_OPERATION      Run_Result = 2
	Run_FAILED_SUCCESS_SIGNAL Run_Result = 3
	Run_SUCCESS               Run_Result = 4
)

// Enum value maps for Run_Result.
var (
	Run_Result_name = map[int32]string{
		0: "UNKNOWN",
		1: "FAILED_PRECONDITION",
		2: "FAILED_OPERATION",
		3: "FAILED_SUCCESS_SIGNAL",
		4: "SUCCESS",
	}
	Run_Result_value = map[string]int32{
		"UNKNOWN":               0,
		"FAILED_PRECONDITION":   1,
		"FAILED_OPERATION":      2,
		"FAILED_SUCCESS_SIGNAL": 3,
		"SUCCESS":               4,
	}
)

func (x Run_Result) Enum() *Run_Result {
	p := new(Run_Result)
	*p = x
	return p
}

func (x Run_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Run_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_datamodel_proto_enumTypes[1].Descriptor()
}

func (Run_Result) Type() protoreflect.EnumType {
	return &file_datamodel_proto_enumTypes[1]
}

func (x Run_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Run_Result.Descriptor instead.
func (Run_Result) EnumDescriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{1, 0}
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamodel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Run struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID    *Key   `protobuf:"bytes,1,opt,name=ActorID,proto3" json:"ActorID,omitempty"`
	DirectorID *Key   `protobuf:"bytes,2,opt,name=DirectorID,proto3" json:"DirectorID,omitempty"`
	Timestamp  uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error      string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Run) Reset() {
	*x = Run{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamodel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{1}
}

func (x *Run) GetActorID() *Key {
	if x != nil {
		return x.ActorID
	}
	return nil
}

func (x *Run) GetDirectorID() *Key {
	if x != nil {
		return x.DirectorID
	}
	return nil
}

func (x *Run) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Run) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RunMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runs []*Run `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
}

func (x *RunMetadata) Reset() {
	*x = RunMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamodel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMetadata) ProtoMessage() {}

func (x *RunMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMetadata.ProtoReflect.Descriptor instead.
func (*RunMetadata) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{2}
}

func (x *RunMetadata) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

type StateMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateId     *Key   `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *StateMetadata) Reset() {
	*x = StateMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamodel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateMetadata) ProtoMessage() {}

func (x *StateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateMetadata.ProtoReflect.Descriptor instead.
func (*StateMetadata) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{3}
}

func (x *StateMetadata) GetStateId() *Key {
	if x != nil {
		return x.StateId
	}
	return nil
}

func (x *StateMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StateMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ActorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      *Key         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Status   ActorStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=orcareduce.model.ActorStatus" json:"status,omitempty"`
	Metadata *RunMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Revision uint64       `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *ActorState) Reset() {
	*x = ActorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamodel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorState) ProtoMessage() {}

func (x *ActorState) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorState.ProtoReflect.Descriptor instead.
func (*ActorState) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{4}
}

func (x *ActorState) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ActorState) GetStatus() ActorStatus {
	if x != nil {
		return x.Status
	}
	return ActorStatus_UNKNOWN_ACTOR_STATE
}

func (x *ActorState) GetMetadata() *RunMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ActorState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_datamodel_proto protoreflect.FileDescriptor

var file_datamodel_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x10, 0x6f, 0x72, 0x63, 0x61, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x1b, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x8f, 0x02, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x2f, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x72, 0x63, 0x61,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4b, 0x65, 0x79,
	0x52, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x0a, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6f, 0x72, 0x63, 0x61, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x6c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x46,
	0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x4f,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x49, 0x47,
	0x4e, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x04, 0x22, 0x38, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x29, 0x0a, 0x04, 0x72, 0x75, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x04, 0x72, 0x75, 0x6e, 0x73, 0x22, 0x77, 0x0a, 0x0d,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a,
	0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc3, 0x01, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x6f, 0x72, 0x63, 0x61, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x75, 0x6e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2a, 0x4e, 0x0a, 0x0b, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x12, 0x5a, 0x10, 0x6f,
	0x72, 0x63, 0x61, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datamodel_proto_rawDescOnce sync.Once
	file_datamodel_proto_rawDescData = file_datamodel_proto_rawDesc
)

func file_datamodel_proto_rawDescGZIP() []byte {
	file_datamodel_proto_rawDescOnce.Do(func() {
		file_datamodel_proto_rawDescData = protoimpl.X.CompressGZIP(file_datamodel_proto_rawDescData)
	})
	return file_datamodel_proto_rawDescData
}

var file_datamodel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_datamodel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_datamodel_proto_goTypes = []interface{}{
	(ActorStatus)(0),      // 0: orcareduce.model.ActorStatus
	(Run_Result)(0),       // 1: orcareduce.model.Run.Result
	(*Key)(nil),           // 2: orcareduce.model.Key
	(*Run)(nil),           // 3: orcareduce.model.Run
	(*RunMetadata)(nil),   // 4: orcareduce.model.RunMetadata
	(*StateMetadata)(nil), // 5: orcareduce.model.StateMetadata
	(*ActorState)(nil),    // 6: orcareduce.model.ActorState
}
var file_datamodel_proto_depIdxs = []int32{
	2, // 0: orcareduce.model.Run.ActorID:type_name -> orcareduce.model.Key
	2, // 1: orcareduce.model.Run.DirectorID:type_name -> orcareduce.model.Key
	3, // 2: orcareduce.model.RunMetadata.runs:type_name -> orcareduce.model.Run
	2, // 3: orcareduce.model.StateMetadata.state_id:type_name -> orcareduce.model.Key
	2, // 4: orcareduce.model.ActorState.key:type_name -> orcareduce.model.Key
	0, // 5: orcareduce.model.ActorState.status:type_name -> orcareduce.model.ActorStatus
	4, // 6: orcareduce.model.ActorState.metadata:type_name -> orcareduce.model.RunMetadata
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_datamodel_proto_init() }
func file_datamodel_proto_init() {
	if File_datamodel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datamodel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamodel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamodel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamodel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamodel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datamodel_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datamodel_proto_goTypes,
		DependencyIndexes: file_datamodel_proto_depIdxs,
		EnumInfos:         file_datamodel_proto_enumTypes,
		MessageInfos:      file_datamodel_proto_msgTypes,
	}.Build()
	File_datamodel_proto = out.File
	file_datamodel_proto_rawDesc = nil
	file_datamodel_proto_goTypes = nil
	file_datamodel_proto_depIdxs = nil
}
